jobs:
  server:
    source:
      localFolder: .
      project: Runner.csproj
    readyStateText: Application started.
    waitForExit: true
scenarios:
  runner:
    application:
      job: server
      options:
        collectCounters: true
profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
  remote-lin:
    jobs: 
      application:
        endpoints: 
          - http://asp-perf-lin:5001
  remote-win:
    jobs: 
      application:
        endpoints: 
          - http://asp-perf-win:5001
scripts:
    adjust_start_time_win: |
        benchmarks.jobs.application.results["benchmarks/start-time"] = benchmarks.jobs.application.results["benchmarks/start-time"] - 500;
        benchmarks.jobs.application.results["benchmarks/start-time"] = benchmarks.jobs.application.results["benchmarks/start-time"] - 500;
    adjust_start_time_lin: |
        benchmarks.jobs.application.results["benchmarks/start-time"] = benchmarks.jobs.application.results["benchmarks/start-time"] - 500;
        benchmarks.jobs.application.results["benchmarks/start-time"] = benchmarks.jobs.application.results["benchmarks/start-time"] - 500;